# 随机字符串
com:
  didispace:
    blog:
      number: ${random.int}
## 随机int
#com.didispace.blog.number=${random.int}
## 随机long
#com.didispace.blog.bignumber=${random.long}
## 10以内的随机数
#com.didispace.blog.test1=${random.int(10)}
## 10-20的随机数
#com.didispace.blog.test2=${random.int[10,20]}