spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
#mybatis
#  mapper-locations
#    classpath*:mapper/*.xml
#mybatis.type-aliases-package=com.oa.entity
mybatis:
  mapper-locations:
  - classpath*:mapper/*.xml
  type-aliases-package: com.zhangyao.entity