server:
  port: 8081
  servlet:
    context-path: /weixin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#mybatis
mybatis:
  type-aliases-package: com.zhangyao.entity
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/mybatis-config.xml 