spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb
    username: root
    password: 123456
  devtools:
    livereload:
      enabled: false
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 0
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 100
        min-idle: 5 
        
      
mybatis:
  type-aliases-package: com.zhangyao.entity
  mapper-locations:
  - classpath:mapper/*.xml